name: Compile ChatDACS for Windows
on:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  build-job:
    name: Build ðŸš€
    runs-on: windows-latest
    steps:
      - name: Set Up Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Remove Other Platforms go-cqhttp
        run: rm ./plugins/go-cqhttp/go-cqhttp

      - name: Clean Install Modules
        run: npm ci --production

      - name: Clean Install For Plugins
        run: |
          cd ./plugins/
          npm ci --production
          rm package.json
          rm package-lock.json
          cd ..

      - name: Install PKG Tool
        run: npm install pkg -g

      - name: Package
        run: pkg . --compress Brotli

      - name: Declare VERSION
        run: echo "VERSION=version.json" >> $GITHUB_ENV

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ChatDACS-${{ env.VERSION.versionNumber }}_windows
          path: |
            ./config/
            ./static/
            ./plugins/
            ./README.md
            ./LICENSE
            ./chatdacs.exe
          if-no-files-found: error
