name: Compile ChatDACS for Windows
on:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  my-job:
    name: Build ğŸš€
    runs-on: windows-latest
    steps:
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Check out code
        uses: actions/checkout@v2

      - name: Clean Install Modules
        run: npm ci --prod

      - name: Install PKG Tool
        run: npm install pkg -g

      - name: Package
        run: pkg . --compress Brotli

      - name: Reinstall Modules For Plugins
        run: |
          npm i request
          npm i yaml
          npm i sqlite3
          npm i require.all
          npm i axios

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ChatDACS
          path: |
            ./node_modules/
            ./config/
            ./static/
            ./plugins/
            ./db.db
            ./README.md
            ./LICENSE
            ./chatdacs.exe
            ./æ–‡ä»¶è·¯å¾„ä¸å¾—å­˜åœ¨éè‹±æ–‡å­—ç¬¦
          if-no-files-found: error
